In [4]:
import numpy as np


np.random.seed(42)

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
Multi-dimensional Arrays

SyntaxError: invalid syntax (342312646.py, line 1)

In [ ]:

np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
n = np.array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
n[1, 1] = 10
n

array([[ 0.,  0.,  0.],
       [ 0., 10.,  0.]])

In [ ]:
n[0] = [1, 2, 3]

In [ ]:
n[:, 1]

array([2., 2.])

Generate Random Arrays

In [ ]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [ ]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [ ]:
np.random.seed(2)
np.random.randint(0, 100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [ ]:
import pandas as pd

pd.__version__

'2.2.2'

DataFrames

In [ ]:
data = pd.read_csv('/home/auto/mlzoomcamp/car_fuel_efficiency.csv')

In [ ]:
data.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [ ]:
data.count()

engine_displacement    9704
num_cylinders          9222
horsepower             8996
vehicle_weight         9704
acceleration           8774
model_year             9704
origin                 9704
fuel_type              9704
drivetrain             9704
num_doors              9202
fuel_efficiency_mpg    9704
dtype: int64

In [ ]:
data.fuel_type.value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

In [ ]:
df = pd.read_csv('/home/auto/mlzoomcamp/car_fuel_efficiency.csv')

In [ ]:
df.loc[[0, 1]]

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217

In [ ]:
df.describe().round(2)

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,num_doors,fuel_efficiency_mpg
count,9704.00,9222.00,8996.00,9704.00,8774.00,9704.00,9202.00,9704.00
mean,199.71,3.96,149.66,3001.28,15.02,2011.48,-0.01,14.99
std,49.46,2.00,29.88,497.89,2.51,6.66,1.05,2.56
min,10.00,0.00,37.00,952.68,6.00,2000.00,-4.00,6.20
25%,170.00,3.00,130.00,2666.25,13.30,2006.00,-1.00,13.27
50%,200.00,4.00,149.00,2993.23,15.00,2012.00,0.00,15.01
75%,230.00,5.00,170.00,3334.96,16.70,2017.00,1.00,16.71
max,380.00,13.00,271.00,4739.08,24.30,2023.00,4.00,25.97

In [ ]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [ ]:
df.horsepower.median()

152.0

In [ ]:
df['horsepower'] = df.horsepower.fillna(df.horsepower.mode()[0])

In [ ]:
df["fuel_efficiency_mpg"].max()

25.96722204888372

In [ ]:
max_efficiency = df[df['origin'] == 'Asia']

In [ ]:
max_efficiency["fuel_efficiency_mpg"].max()

23.759122836520497

In [ ]:
df.horsepower.median()

152.0

In [ ]:
df[['horsepower']]

      horsepower
0          159.0
1           97.0
2           78.0
3          152.0
4          140.0
...          ...
9699       164.0
9700       154.0
9701       138.0
9702       177.0
9703       140.0

[9704 rows x 1 columns]

In [ ]:
X = df[['vehicle_weight', 'model_year']].head(7)

In [ ]:
X.values

array([[3413.43375861, 2003.        ],
       [3149.66493422, 2007.        ],
       [3079.03899737, 2018.        ],
       [2542.39240183, 2009.        ],
       [3460.87098999, 2009.        ],
       [2484.88398604, 2008.        ],
       [3006.54228722, 2012.        ]])

In [ ]:
asian_cars = df[df['origin'] == 'Asia']

In [ ]:
asian_cars = asian_cars[['vehicle_weight', 'model_year']]

In [ ]:
X = asian_cars.head(7).values

In [ ]:
XTX = X.T @ X
XTX_inv = np.linalg.inv(XTX)

In [ ]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [ ]:
w = XTX_inv @ X.T @ y

In [ ]:
w_sum = w.sum()
print(w_sum)

0.5187709081074007

FULL CODE in a single cell

In [ ]:
asian_cars = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)
X = asian_cars.values
XTX = X.T @ X
XTX_inv = np.linalg.inv(XTX)
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = XTX_inv @ X.T @ y
w.sum()

0.5187709081074007